/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/events': RouteRecordInfo<'/events', '/events', Record<never, never>, Record<never, never>>,
    '/research_achievements': RouteRecordInfo<'/research_achievements', '/research_achievements', Record<never, never>, Record<never, never>>,
    '/research_overview': RouteRecordInfo<'/research_overview', '/research_overview', Record<never, never>, Record<never, never>>,
    '/resources': RouteRecordInfo<'/resources', '/resources', Record<never, never>, Record<never, never>>,
    '/team': RouteRecordInfo<'/team', '/team', Record<never, never>, Record<never, never>>,
  }
}
